SUPER-MEGA-PUPER-GIGA-EXTRA-REFUCKTORING
spbu-math-cs/ig-platform pull request #88
Opened 2023-12-10 14:51 UTC by volivan239

2023-12-10 22:34 UTC, netkex requested changes
Получилось просто 🔥🔥🔥, но немного не хватает документации в коде

2023-12-10 22:34 UTC, netkex commented on clvr-back/platform/src/main/kotlin/com/clvr/platform/api/ClvrSessionRegistry.kt
> +interface ClvrSessionRegistry<Req: EventPayloadInterface, Resp: EventPayloadInterface> {
Возможно стоит добавить комментарий, почему этот интерфейс разделен с `SessionStorage`. 

Еще может было бы круто/удобно в комментариях или какой-то своей аннотацией указать какие методы торчат наружу для реализации новой игры, а какие служебные и чисто внутренние. Но это скорее на будущее)

2023-12-10 22:34 UTC, netkex commented on clvr-back/platform/src/main/kotlin/com/clvr/platform/util/SessionManager.kt
> +): AutoCloseable, SessionParticipantsCommunicator<Req, Resp> {
Мб сделать `InMemorySessionParticipantsCommunicator` на подобие `SessionStorage`. Чтобы была сразу явная ассоциация с интерфейсом?

2023-12-10 22:34 UTC, netkex commented on clvr-back/platform/src/main/kotlin/com/clvr/platform/util/SessionManager.kt
> +package com.clvr.platform.util
Думаю стоит этот класс добавить ко всем в `impl`

2023-12-10 22:34 UTC, netkex commented on clvr-back/tic-tac-toe/src/main/kotlin/com/clvr/ttt/TicTacToeGameController.kt
> +typealias TicTacToeSessionParticipantsCommunicator =
Реализация игры с использованием платформы выглядит как чистый кайф

2023-12-12 12:37 UTC, volivan239 commented on clvr-back/platform/src/main/kotlin/com/clvr/platform/api/db/TemplateDatabase.kt
> +}
добавил комментарий

2023-12-12 12:37 UTC, volivan239 commented on clvr-back/platform/src/main/kotlin/com/clvr/platform/api/ActivityInstaller.kt
> +    val activityId: String
Сделал `activityName`, называть это `game` не хочется, т.к. это слово и так у нас уже перегружено

2023-12-12 12:38 UTC, volivan239 commented on clvr-back/platform/src/main/kotlin/com/clvr/platform/api/Events.kt
> +    override val payload: T
Всегда должно отсутствовать, это косяк, завел #93 под это

2023-12-12 12:38 UTC, volivan239 commented on clvr-back/platform/src/main/kotlin/com/clvr/platform/api/ClvrSessionRegistry.kt
> +    val clientView: List<ResponseEvent<Resp>>
Да (ну и вроде это имеет смысл), добавил комментарий про это

2023-12-12 12:38 UTC, volivan239 commented on clvr-back/platform/src/main/kotlin/com/clvr/platform/impl/db/PostgresTemplateDatabase.kt
> +    }
Докинул

2023-12-12 12:39 UTC, volivan239 commented on clvr-back/platform/src/main/kotlin/com/clvr/platform/api/ClvrSessionRegistry.kt
> +interface ClvrSessionRegistry<Req: EventPayloadInterface, Resp: EventPayloadInterface> {
Постарался расписать все в доке к `SessionStorage`

2023-12-12 12:40 UTC, volivan239 commented on clvr-back/platform/src/main/kotlin/com/clvr/platform/util/SessionManager.kt
> +): AutoCloseable, SessionParticipantsCommunicator<Req, Resp> {
Ну не знаю, мне название `Manager` больше нравилось, у него все-таки более широкий интерфейс чем `Communicator`...

2023-12-12 12:40 UTC, volivan239 commented on clvr-back/platform/src/main/kotlin/com/clvr/platform/util/SessionManager.kt
> +package com.clvr.platform.util
Ага, закинул его в `impl`, осталось только убрать зависимость на него в других модулях

2023-12-12 12:54 UTC, merged