[backend] support nekahoot
spbu-math-cs/ig-platform pull request #96
Opened 2023-12-13 23:20 UTC by frungl

linked to #91

2023-12-14 10:07 UTC, volivan239 commented on clvr-back/nekahoot/src/main/kotlin/com/clvr/nk/NeKahootEvents.kt
> +    val answer_options: List<String>,
Я все-таки за то, чтобы в котлиновском коде все было в CamelCase, а имя при сериализации задавалось с помощью `@SerialName`, но пока это для демо -- ок

2023-12-14 10:20 UTC, volivan239 commented on clvr-back/nekahoot/src/main/kotlin/com/clvr/nk/NeKahootEvents.kt
> +}
Согласно документации поле `payload` вообще должно отсутсововать в запросах типа `NEXT_QUESTION`. Поэтому если тебе придет такой запрос с отсутствующим `payload`, ты не сможешь его десериализовать (у тебя будет выпадет исключение где-то в `decodeJsonToNKEvent`). 

Ожидаемый способ решения был таким: сделать `NeKahootRequest` `sealed`-интерфейсом, а то что сейчас им называется, сделать его имплементаций (назвать, например `NeKahootRequestWithPayload<T: NeKahootRequestPayload>`), а для запросов вида `NEXT_QUESTION` сделать другую имплементацию того интерфейса (условно, `object NextQuestionRequest : NeKahootRequest`, и в десериализаторе если видеть `NEXT_QUESTION` сразу возвращать этот `object`.

Можно как-нибудь и по-другому решить, главное, чтобы можно было десериализовать json без поля `payload` для таких запросов

2023-12-14 10:23 UTC, volivan239 commented on clvr-back/nekahoot/src/main/kotlin/com/clvr/nk/NeKahootGameView.kt
> +        get() = listOf()
Получается, что только что подключившиеся хост/клиент не получат никаких ивентов, отражающих состояние игры на момент подключения?

2023-12-14 10:24 UTC, frungl commented on clvr-back/nekahoot/src/main/kotlin/com/clvr/nk/NeKahootEvents.kt
> +}
Да, это пока временное решение, хочу сначала убедиться что вся логика правильно работает, а потом уже причесать протокол общения

2023-12-14 10:24 UTC, volivan239 requested changes
Супер, что ты подтянул изменения из #93, вообще все выглядит хорошо, посмотри комменты, пожалуйста

2023-12-14 10:30 UTC, frungl commented on clvr-back/nekahoot/src/main/kotlin/com/clvr/nk/NeKahootGameView.kt
> +        get() = listOf()
В начале игры это не важно, так как информацию о вопросах мы получим только после ивента START_GAME, а до этого непонятно что, можно ещё сделать статус с количеством подключенных игроков, но это не первой важности. Видимо было бы хорошо сделать так, что бы при подключении во время игры было получено текущее состояние, но опять же это после того как я напишу тесты к основной логике

2023-12-24 10:43 UTC, elteammate commented
superseded in #109

2023-12-24 10:43 UTC, closed without merging